In [1]:
import pandas as pd
import numpy as np

data = pd.read_csv('train.csv')
data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [2]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     1452 non-null   object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [3]:
data.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [7]:
data.isna().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ...
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 81, dtype: int64

In [9]:
missing_features = data.columns[data.isna().any()].tolist()
print("Eksik veri iÃ§eren feature'lar:\n", missing_features)

Eksik veri iÃ§eren feature'lar:
 ['LotFrontage', 'Alley', 'MasVnrType', 'MasVnrArea', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Electrical', 'FireplaceQu', 'GarageType', 'GarageYrBlt', 'GarageFinish', 'GarageQual', 'GarageCond', 'PoolQC', 'Fence', 'MiscFeature']

In [13]:
most_common_Lot = data['LotFrontage'].mode()[0]
data['LotFrontage'] = data['LotFrontage'].fillna(most_common_Lot)

most_common_Alley = data['Alley'].mode()[0]
data['Alley'] = data['Alley'].fillna(most_common_Alley)

most_common_MasVnrType = data['MasVnrType'].mode()[0]
data['MasVnrType'] = data['MasVnrType'].fillna(most_common_MasVnrType)

most_common_MasVnrArea = data['MasVnrArea'].mode()[0]
data['MasVnrArea'] = data['MasVnrArea'].fillna(most_common_MasVnrArea)

most_common_BsmtQual = data['BsmtQual'].mode()[0]
data['BsmtQual'] = data['BsmtQual'].fillna(most_common_BsmtQual)

most_common_BsmtCond = data['BsmtCond'].mode()[0]
data['BsmtCond'] = data['BsmtCond'].fillna(most_common_BsmtCond)

most_common_BsmtExposure = data['BsmtExposure'].mode()[0]
data['BsmtExposure'] = data['BsmtExposure'].fillna(most_common_BsmtExposure)

most_common_BsmtFinType1 = data['BsmtFinType1'].mode()[0]
data['BsmtFinType1'] = data['BsmtFinType1'].fillna(most_common_BsmtFinType1)

most_common_BsmtFinType2 = data['BsmtFinType2'].mode()[0]
data['BsmtFinType2'] = data['BsmtFinType2'].fillna(most_common_BsmtFinType2)

most_common_Electrical = data['Electrical'].mode()[0]
data['Electrical'] = data['Electrical'].fillna(most_common_Electrical)

most_common_FireplaceQu = data['FireplaceQu'].mode()[0]
data['FireplaceQu'] = data['FireplaceQu'].fillna(most_common_FireplaceQu)

most_common_GarageType = data['GarageType'].mode()[0]
data['GarageType'] = data['GarageType'].fillna(most_common_GarageType)

most_common_GarageYrBlt = data['GarageYrBlt'].mode()[0]
data['GarageYrBlt'] = data['GarageYrBlt'].fillna(most_common_GarageYrBlt)

most_common_GarageFinish = data['GarageFinish'].mode()[0]
data['GarageFinish'] = data['GarageFinish'].fillna(most_common_GarageFinish)

most_common_GarageQual = data['GarageQual'].mode()[0]
data['GarageQual'] = data['GarageQual'].fillna(most_common_GarageQual)

most_common_GarageCond = data['GarageCond'].mode()[0]
data['GarageCond'] = data['GarageCond'].fillna(most_common_GarageCond)

most_common_PoolQC = data['PoolQC'].mode()[0]
data['PoolQC'] = data['PoolQC'].fillna(most_common_PoolQC)

most_common_Fence = data['Fence'].mode()[0]
data['Fence'] = data['Fence'].fillna(most_common_Fence)

most_common_MiscFeature = data['MiscFeature'].mode()[0]
data['MiscFeature'] = data['MiscFeature'].fillna(most_common_MiscFeature)

In [14]:
missing_features = data.columns[data.isna().any()].tolist()
print("Eksik veri iÃ§eren feature'lar:\n", missing_features)

Eksik veri iÃ§eren feature'lar:
 []

In [16]:
data = pd.get_dummies(data,drop_first=True)
data.head()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,SaleType_Oth,SaleType_WD,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial,BsmtCondl_Gd,BsmtCondl_Po,BsmtCondl_TA
0,1,60,65.0,8450,7,5,2003,2003,196.0,706,...,0,1,0,0,0,1,0,0,0,1
1,2,20,80.0,9600,6,8,1976,1976,0.0,978,...,0,1,0,0,0,1,0,0,0,1
2,3,60,68.0,11250,7,5,2001,2002,162.0,486,...,0,1,0,0,0,1,0,0,0,1
3,4,70,60.0,9550,7,5,1915,1970,0.0,216,...,0,1,0,0,0,0,0,1,0,0
4,5,60,84.0,14260,8,5,2000,2000,350.0,655,...,0,1,0,0,0,1,0,0,0,1

In [17]:
from sklearn.feature_selection import SelectKBest, f_regression

X = data.drop('SalePrice', axis=1)
Y = data['SalePrice']

selector = SelectKBest(score_func=f_regression, k=5)
X_selected = selector.fit_transform(X, Y)

selected_indices = selector.get_support(indices=True)

selected_features = X.columns[selected_indices]

print("Selected Features:")
print(selected_features)

Selected Features:
Index(['OverallQual', 'TotalBsmtSF', 'GrLivArea', 'GarageCars', 'GarageArea'], dtype='object')

In [18]:
from sklearn.model_selection import train_test_split

X = data[['OverallQual', 'TotalBsmtSF', 'GrLivArea', 'GarageCars', 'GarageArea']]
y = data['SalePrice']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.35, shuffle=True)

In [19]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

In [20]:
train_accuracy = model.score(X_train, y_train)
test_accuracy = model.score(X_test, y_test)

print("EÄŸitim DoÄŸruluÄŸu:", train_accuracy)
print("Test DoÄŸruluÄŸu:", test_accuracy)

EÄŸitim DoÄŸruluÄŸu: 0.9734238355339481
Test DoÄŸruluÄŸu: 0.7789391407267279